
### Get all users

GET /api/v1/users HTTP/1.1
Host: localhost:8080
Accept: application/json

### Create a new User

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "batata@potato.com",
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Post an invalid user

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Get all islands

GET /api/v1/islands HTTP/1.1
Host: localhost:8080
Accept: application/json

### Create a new Island

POST /api/v1/islands HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "description": "Island A",
    "disposition": "RECTANGLE",
    "workstations": [
        {
            "specs": "Intel i7, 16GB RAM, 512GB SSD"
        },
        {
            "specs": "Intel i5, 8GB RAM, 256GB SSD"
        }
    ]
}

### Allocate a workstation to a user
PATCH /api/v1/islands/allocate HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "userId": 5
}