
### Get all users

GET /api/v1/users HTTP/1.1
Host: localhost:8080
Accept: application/json

### Create a new User

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "evelyn@potato.com",
    "password": "1234RT56",
    "handle": "evelyn",
    "name": "Evelyn",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Create a new User

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "bruno@gmail.com",
    "password": "abc12356",
    "handle": "bruno",
    "name": "bruno",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Post an invalid user

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Post ticket

POST /api/v1/tickets HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "creator": 2,
    "destinatary": 2,
    "item": "pc",
    "to_do": "consertar",
    "details": "quero um pc bom",
    "place": "if"
}

### Post ticket

POST /api/v1/tickets HTTP/1.1
Host: localhost:8081
Content-Type: application/json

{
    "creator": 2,
    "destinatary": 2,
    "item": "computador",
    "to_do": "atualizar",
    "details": "atualizar o sistema",
    "place": "if"
}

### Get all tickets

GET /api/v1/tickets HTTP/1.1
Host: localhost:8081
Accept: application/json

### Patch ticket

PATCH /api/v1/tickets/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "status": "Andamento"
}